CREATE TABLE IF NOT EXISTS addresses (
  id SERIAL UNIQUE PRIMARY KEY,
  u_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  addr_1 TEXT NOT NULL,
  addr_2 TEXT,
  zip TEXT NOT NULL,
  city TEXT NOT NULL,
  country TEXT NOT NULL,
  is_default BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);